config/routes.rb
MasterClassNB::Application.routes.draw do
  get "teacher_subjects/index"
  get "teacher_subjects/show"
  get "teacher_subjects/new"
  get "teacher_subjects/create"
  get "teacher_subjects/edit"
  get "teacher_subjects/destroy"
  get "teacher_subjects/update"
  get "sessions/create"
  get "sessions/destroy"
  get "register_subjects/index"
  get "register_subjects/edit"
  get "register_subjects/create"
  get "subjects/new"
  get "subjects/index"
  get "subjects/edit"
  get "subjects/create"
  get "programs/create"
  get "programs/new"
  get "programs/index"
  get "programs/edit"
  get "semesters/new"
  get "semesters/index"
  get "semesters/edit"
  get "semesters/show"
  get "semesters/create"
  
  get "users/new"
  get "users/index"
  get "users/edit"
  get "users/show"
  
  
  match "estadisticas", to: 'estadisticas#index', via: 'get'
  match "users/cargar_usuarios", to: 'users#cargar_usuarios', via: 'get'
  match "users/mostrar", to: 'users#ver', via: 'get'
  
  

  match '/help', to: 'general#help', via: 'get'
  match '/about',   to: 'general#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  match '/preregister_subjects', to: 'preregister_subjects#update',     via: 'patch'  
  match '/preregister_subjects', to: 'preregister_subjects#destroy',     via: 'delete'  

  root 'sessions#new'
  
  resources :users
  resources :programs
  resources :subjects
  resources :semesters
  resources :preregister_subjects
  resources :sessions, only: [:new, :create, :destroy]

  

end

app/models/program.rb
class Program < ActiveRecord::Base
  before_save { self.code = code.upcase }
  
  validates :name, presence: true, length: { maximum: 200 }
  validates :code, presence: true, length: { maximum: 100 },  uniqueness: { case_sensitive: false }
  validates :objective, presence: true, length: { maximum: 500 }
  validates :status, presence: true

  has_many :program_semesters
  has_many :semesters, :through => :program_semesters
  
  has_many :user_programs
  has_many :users, :through => :user_programs
  
  has_many :subject_programs
  has_many :subjects, :through => :subject_programs
  
  belongs_to :user

  has_many :preregister_subjects
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def new
    @program = Program.new
  end

  def index
    @program_list =  Program.paginate(page: params[:page]).per_page(10)
  end

  def edit
    @program = Program.find(params[:id])
  end
  
  def show
    if !params[:disable].nil?
      @program = Program.find(params[:id])
      if params[:disable] == "1"       
        @program.update_attribute(:status, "Inactivo")
        flash[:success] = I18n.t('programa.deshabilitado') 
      else       
        @program.update_attribute(:status, "Activo")
        flash[:success] = I18n.t('programa.habilitado')
      end
    end
    redirect_to programs_url
  end
  
  def update
    @program = Program.find(params[:id])
    if @program.update_attributes(program_params)       
      flash[:success] = "La informacion del programa se ha actualizado exitosamente"
      redirect_to programs_url
    else
      flash[:error]="Ocurrio un error al editar el usuario"
      render 'edit'
    end
  end

  def create
    @program = Program.new(program_params)    
    if @program.save
      flash[:success] = 'Mensaje de exito'
      redirect_to programs_url
    else     
      flash[:error] = 'Ha ocurrido un error'
      render 'new'
    end
  end
  
  
  
  def program_params
    params.require(:program).permit(:name,:code,:objective,:status)
      
  end
  
  def signed_in_user
    redirect_to signin_url, notice: "Por favor ingrese antes de poder realizar esta acción" unless signed_in?
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_program.html.erb
<% if !@verusr.nil? && @verusr.eql?("1") %>
  <tr>
    <td><%= "#{program.code}" %></td>
    <td><%= "#{program.name}" %></td>
    <%if (@user.usertype.eql?("Estudiante") || coordinador?)%>
      <% if !@user.preregister_subjects.where(program_id: program.id).any? %>
        <td>  <%= link_to I18n.t('programas.autoregistro'), preregister_subjects_path(:automatic => 1,:user_id =>@user.id,:program_id =>program.id), method: :patch, data: { confirm: I18n.t('seguro')} %></td>
      <% else %>
        <td>  <%= link_to I18n.t('programas.mostrar'), preregister_subjects_path(:user_id =>@user.id,:program_id =>program.id), method: :get %></td>
      <% end %>
      <% if  @user.preregister_subjects.where(program_id: program.id).count < 10 %>
        <td>  <%= link_to I18n.t('programas.preregistrar'), new_preregister_subject_path(:user_id =>@user.id,:program_id =>program.id), method: :get %></td>
      <% end %>
    <% end %>
  </tr>
<% else %>
  <tr>
    <td><%= "#{program.code}" %></td>
    <td><%= "#{program.name}" %></td>
    <td><%= "#{program.status}" %></td>
    <% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
      <td>
        <%= link_to  image_tag(('log_eliminar.png'), alt: I18n.t('delete')), program, method: :delete,  data: { confirm: I18n.t('seguro') } %>
      </td>
      <td>
        <%= link_to link_to image_tag(('log_editar.png'), alt: I18n.t('editar')),  edit_program_path(program) %>
      </td>
      <td>
        <% if program.status == "Activo" %>
          <%= link_to image_tag(('log_desactivar.png'), alt: I18n.t('disable')), program_path(program,:disable => 1), data: { confirm: I18n.t('seguro') } %>
        <% end %>
        <% if program.status == "Inactivo" %>
          <%= link_to image_tag(('log_desactivar.png'), alt: I18n.t('enable')), program_path(program,:disable => 0),          data: { confirm: I18n.t('seguro') }  %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/programs/create.html.erb
<h1>Programs#create</h1>
<p>Find me in app/views/programs/create.html.erb</p>

app/views/programs/edit.html.erb
<% provide(:title, 'Editar programa') %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;max-width:480px;min-width:150px">
  <div class="title">
    <h1>Editar programa</h1>
  </div>
  <div class="span6 offset3" >
    <%= form_for(@program) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>


      <%= f.label :code %>
      <%= f.text_field :code %>


      <%= f.label :objective %>
      <%= f.text_area :objective%>

      <%= f.label :status %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   



      <div class="submit">
        <%= f.submit "Editar programa", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/programs/index.html.erb
<% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
  <div id="main1">
    <div id="main2">
      <div id="left">
        <div class="column-in">
          <h2>
            <p id="lccont" class="btn">
              <%= link_to image_tag('log_agregar.png')+"Agregar programa nuevo", programs_new_path %>
            </p>
          </h2>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% unless @program_list.nil? %>
  <% if @program_list.size>0 %>
    <table  border="1">
      <th>Código</th>
      <th>Nombre</th>
      <th>Estado</th>
      <% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
        <th colspan="3">Acciones</th>
      <% end %>

      <%= render @program_list %>
    </table>
    <%= will_paginate @program_list  %>
  <% else %> 
    <p>No existen programas disponibles</p>
  <% end %>  
<% end %>

app/views/programs/new.html.erb
<% provide(:title, 'Agregar programa') %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;max-width:480px;min-width:150px">
  <div class="title">
    <h1>Agregar programa</h1>
  </div>
  <div class="span6 offset3" >
    <%= form_for(@program) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>


      <%= f.label :code %>
      <%= f.text_field :code %>


      <%= f.label :objective %>
      <%= f.text_area :objective%>

      <%= f.label :status %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   



      <div class="submit">
        <%= f.submit "Agregar programa", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>