config/routes.rb
MasterClassNB::Application.routes.draw do
  get "teacher_subjects/index"
  get "teacher_subjects/show"
  get "teacher_subjects/new"
  get "teacher_subjects/create"
  get "teacher_subjects/edit"
  get "teacher_subjects/destroy"
  get "teacher_subjects/update"
  get "sessions/create"
  get "sessions/destroy"
  get "register_subjects/index"
  get "register_subjects/edit"
  get "register_subjects/create"
  get "subjects/new"
  get "subjects/index"
  get "subjects/edit"
  get "subjects/create"
  get "programs/create"
  get "programs/new"
  get "programs/index"
  get "programs/edit"
  get "semesters/new"
  get "semesters/index"
  get "semesters/edit"
  get "semesters/show"
  get "semesters/create"
  
  get "users/new"
  get "users/index"
  get "users/edit"
  get "users/show"
  
  
  match "estadisticas", to: 'estadisticas#index', via: 'get'
  match "users/cargar_usuarios", to: 'users#cargar_usuarios', via: 'get'
  match "users/mostrar", to: 'users#ver', via: 'get'
  
  

  match '/help', to: 'general#help', via: 'get'
  match '/about',   to: 'general#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  match '/preregister_subjects', to: 'preregister_subjects#update',     via: 'patch'  
  match '/preregister_subjects', to: 'preregister_subjects#destroy',     via: 'delete'  

  root 'sessions#new'
  
  resources :users
  resources :programs
  resources :subjects
  resources :semesters
  resources :preregister_subjects
  resources :sessions, only: [:new, :create, :destroy]

  

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  validates :firstname,  presence: true, length: { maximum: 100 }
  validates :lastname, presence: true, length: { maximum: 100 }
  validates :identificationtype, presence: true
  validates :identification, presence: true, length: { maximum: 20 }
  validates :status, presence: true
  validates :usertype, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  
  has_secure_password
  
  def admin?
    self.usertype == "Coordinador"
  end 
  
  has_many :user_programs
  has_many :programs, :through => :user_programs
  
  has_many :teacher_subjects
  has_many :subjects, :through => :teacher_subjects
  
  
  has_many :subject_records, :class_name => 'SubjectRecord', :foreign_key => 'user_student_id'
  has_many :preregister_subjects
  
  has_one :program
  
  
  
end

app/controllers/users_controller.rb
#require 'httparty'
require 'rubygems'
require 'json'

class UsersController < ApplicationController
  include HTTParty
  #  before_action :signed_in_user
  def ver
    @user = User.find(params[:id])
    @program = Program.find_by_id(params[:program_id])
    @programs = @user.programs.paginate(page: params[:page], :per_page => 3)
    @subject_records = @user.subject_records.paginate(page: params[:page])
    @preregister_subjects = @user.preregister_subjects.where(program_id: params[:program_id]).paginate(page: params[:page])
    @verusr = "1"

  end
  
  
  def cargar_usuarios
    response = self.class.get("http://184.72.239.150:3000/get_json")
    #    response.to_str
    @parsed_and_a_hash = JSON.parse(response.body)
    #    flash[:error]=@parsed_and_a_hash.count
    @parsed_and_a_hash.each do |key, value|
      #      flash[:error]=key
      #      Codigo de la maestria KEY
      @program = Program.find_by_code(key) 
      if @program.nil?
        Program.create!( name: "Edit me", code:key, objective:"Edit me", status:"Activo")
      end
      
      value.each do |key1,value1|
        #          Cada estudiante por codigo
        
        @codigo= key1
        @user1 = User.find_by_code(@codigo) 
       
        value1.each do |key2,value2|
          #            materias y nombre
         
          if(key2.eql?("subjects"))
          
            @subjects_arr=Array.new(value2.count)
            @subjects =value2
            @subjects.each do |sbj|
              @subjects_arr.push(sbj)
            end
            
          else if(key2.eql?("name"))
              @name = value2
            end
          end
        end
        if @user1.nil? 
          code=@codigo
          firstname=@name
          lastname='Edit me'
          password='123456'
          email='@uniandes.edu.co'
          email = @codigo+email
          identification='123456'
          begin
            User.create!(firstname:firstname, lastname:lastname, code:code, 
              identificationtype:"CC", identification:identification, status:"Activo", 
              usertype:"Estudiante", password:password, password_confirmation:password, email:email)
            
            @program = Program.find_by_code(key) 
            @user1 = User.find_by_code(@codigo) 
            user_programs = UserProgram.new(program_id: @program.id, user_id: @user1.id, status: "Activo")
            if user_programs.valid?
              user_programs.save
            else
              flash.now[:error] = 'No se puede guadar el programa del usuario'
              #@errors += user_programs.errors
            end 
          rescue
            logger.error($!.to_s)
          end
          #  TODO          crear materias no existentes
          #
          #          @subjects = Subject.all
          #            
          #          @subjects.each do |sbj|
          #            @encontro = false
          #            @subjects_arr.each do |sbjenc|
          #              if sbj.code.eql?(sbjenc) 
          #                @encontro = true
          #              end
          #            end
          #            if !@encontro
          #              begin
          #                Subject.create!(name: "Edit me", code:sbjenc, quota:30, credits:3, status:"Activo")
          #              rescue
          #                logger.error($!.to_s)
          #              end
          #            end
          #          end
          #          #            Asociar materias a estudiantes
          #          #            @subjects = TeacherSubject.joins(:user).joins(:subject).select("subjects.*")
          #          #              validates :user_id, presence: true
          #          #  validates :subject_id, presence: true
          #          #  validates :status, presence: true
          #          @subjects = TeacherSubject.joins(:user).joins(:subject).select("subjects.*")
          #            
          #          @user1 = User.find_by_code(@codigo)
          #            
          #          @subjects_arr.each do |sbjenc|
          #            @encontro = false
          #            @subjects.each do |sbj|
          #              if sbj.code.eql?(sbjenc) 
          #                @encontro = true
          #              end
          #            end
          #            if !@encontro
          #              @subject = Subject.find_by_code(sbjenc)
          #              TeacherSubject.create(user_id: @user1.id, subject_id: @subject.id, status: "Visto")
          #            end
          #          end
          #          
          #        else
          #          flash[:error] = "Actualizar usuario"
          #          
          #          user = User.find_by(code: @codigo)
          #          
          #          @usrssubj =  TeacherSubject.joins(:user).joins(:subject).select("subjects.*")
          
        end
      end
    end
    flash[:success]="Usuarios cargados exitosamente"
    redirect_to users_url
    
  end
  def new
    @user = User.new
  end

  def index
    @user_list =  User.paginate(page: params[:page]).per_page(10)
  end

  def edit
    @user = User.find(params[:id])
    @programs = @user.programs
    @programs_ids=Array.new(@programs.count)
    @programs.each do |program|
      @programs_ids.push(program.id)
    end
  end

  def show
    if !params[:disable].nil?
      if params[:disable] == "1"
        @user = User.find(params[:id])
        @user.update_attribute(:status, "Inactivo")
        flash[:success] = I18n.t('usuario.deshabilitado') 
      else
        @user = User.find(params[:id])
        @user.update_attribute(:status, "Activo")
        flash[:success] = I18n.t('usuario.habilitado')
      end
    end
    redirect_to users_url
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      
      UserMailer.welcome_email(@user).deliver
      
      params[:programs].each do |program|
        user_programs = UserProgram.new(program_id: program, user_id: @user.id, status: "Activo")
        if user_programs.valid?
          user_programs.save
          flash[:success] = 'Usuario creado exitosamente'
        else
          flash.now[:error] = 'No fue posible guardar los programas del usuario'
          #@errors += user_programs.errors
        end 
      end
     
      redirect_to users_url
    else
      if @user.code.nil?
        flash[:error] = 'no hay codigo de usuario, por favor ingreselo'
        elseif @user.password.nil
        flash[:error] = 'el password no puede ser vacio'
      else
      end
      render 'new'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = I18n.t('usuario.eliminado') 
    redirect_to users_url
  end
  
  def disable
    @user = User.find(params[:id])
    @user.update_attribute(:status, "Inactivo")
    flash[:success] = I18n.t('usuario.deshabilitado')      
  end
  
  def update
    @user = User.find(params[:id])  
    if @user.update_attributes(user_params)
        
      params[:programs].each do |program|
        user_programs = UserProgram.new(program_id: program, user_id: @user.id, status: "Activo")
        if user_programs.valid?
          user_programs.save          
        else
          flash.now[:error] = 'No fue posible guardar los programas del usuario'
          #@errors += user_programs.errors
        end 
      end
      flash[:success] = "La informacion del usuario se ha actualizado exitosamente"
      #        sign_in @user
      redirect_to users_url
    else
      flash[:error]="Ocurrio un error al editar el usuario"
      render 'edit'
    end
  end
  
  def user_params
    params.require(:user).permit(:firstname,:lastname,:code,:identificationtype,:identification,:status,:usertype, :email, 
      :password,:password_confirmation)
      
  end
  
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_program1.html.erb
  <li>
    <%= program.name %>
   <%= program.code %>
    <%if (@user.usertype.eql?("Estudiante") || coordinador?)%>
      <% if !@user.preregister_subjects.where(program_id: program.id).any? %>
         <%= link_to I18n.t('programas.autoregistro'), preregister_subjects_path(:automatic => 1,:user_id =>@user.id,:program_id =>program.id), method: :patch,
          data: { confirm: I18n.t('seguro')} %>
      <% else %>
        | <%= link_to I18n.t('programas.mostrar'), preregister_subjects_path(:user_id =>@user.id,:program_id =>program.id), method: :get %>
      <% end %>
      <% if  @user.preregister_subjects.where(program_id: program.id).count < 10 %>
        | <%= link_to I18n.t('programas.preregistrar'), new_preregister_subject_path(:user_id =>@user.id,:program_id =>program.id), method: :get %>
      <% end %>
    <% end %>
  </li>

app/views/users/_user.html.erb
<tr>
  <td><%= "#{user.firstname}" %></td>
  <td><%= "#{user.email}" %></td>

  <% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
    <td><%= "#{user.status}" %></td>
    <td>
      <%= link_to image_tag(('log_eliminar.png'), alt: I18n.t('delete')), user, method: :delete,  data: { confirm: I18n.t('seguro') } %>
    </td>
    <td><%= link_to image_tag(('log_editar.png'), alt: I18n.t('editar')),  edit_user_path(user) %></td>
    <td>
      <% if user.status == "Activo" %>
        <%= link_to image_tag(('log_desactivar.png'), alt: I18n.t('disable')) , user_path(user,:disable => 1),
          data: { confirm: I18n.t('seguro') } %>
      <% end %>
      <% if user.status == "Inactivo" %>
        <%= link_to image_tag(('log_desactivar.png'), alt: I18n.t('enable')), user_path(user,:disable => 0),
          data: { confirm: I18n.t('seguro') }  %>
      <% end %>
    </td>
  <% end %>
  <td>
    <%= link_to image_tag(('log_ver.png'), alt: I18n.t('enable')),  users_mostrar_path(user,:id => user.id)  %>
  </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, 'Editar usuario') %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;max-width:480px;min-width:150px">
  <div class="title">
    <h1>Editar usuario</h1>
  </div>
  <div class="span6 offset3" >
    <%= form_for(@user) do |f| %>


      <%= f.label :firstname %>
      <%= f.text_field :firstname %>

      <%= f.label :lastname %>
      <%= f.text_field :lastname %>

      <%= f.label :code %>
      <%= f.text_field :code %>

      <%= f.label :identificationtype, "Identification Type" %>
      <%=f.select(:identificationtype,options_for_select([["CC", "CC"], ["CE", "CE"]]))%>       

      <%= f.label :identification %>
      <%= f.text_field :identification %>

      <%= f.label :status %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   

      <%= f.label :usertype,"User Type" %>
      <%=f.select(:usertype,options_for_select([["Estudiante", "Estudiante"], ["Coordinador", "Coordinador"], ["Profesor", "Profesor"]]))%>   

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :programs %>
      <%= select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name',  {selected: @programs_ids,disabled: @programs_ids}), :multiple => (if :usertype then true else"Estudiante".eql?"Estudiante" end) %>
    
      <div class="submit">
        <%= f.submit "Editar usuario", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
  <div id="main1">
    <div id="main2">
      <div id="left">
        <div class="column-in">
          <h2>
            <p id="lccont" class="btn">
              <%= link_to image_tag('log_agregar.png')+" Agregar usuario", users_new_path %> 
            </p>
          </h2>
        </div>
      </div>
      <%  if current_user.usertype.eql?("Admin") %>
        <div id="middle">
          <div class="column-in" style="padding-left: 10px;">
            <h2>  
              <p id="mccont"  class="btn"> 
                <%= link_to image_tag('iconosubir-03.png')+"Cargar usuarios", users_cargar_usuarios_path %> 
              </p>
            </h2>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<% unless @user_list.nil? %>
  <table  border="1">
    <tr>

      <th>Nombre</td>
      <th>e-mail</td>

        <% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin")%>

        <th>Estado</td>

        <th colspan="4">Acciones</td>
        <% else %>
        <th >Acciones</td> 
        <% end %>
    </tr>

    <%= render @user_list %>
  </table>
  <%= will_paginate @user_list  %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Agregar usuario') %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;max-width:480px;min-width:150px">
  <div class="title">
    <h1>Agregar usuario</h1>
  </div>
  <div class="span6 offset3" >
    <%= form_for(@user) do |f| %>
  <%#= render 'shared/error_messages' %>


      <%= f.label :firstname %>
      <%= f.text_field :firstname %>

      <%= f.label :lastname %>
      <%= f.text_field :lastname %>

      <%= f.label :code %>
      <%= f.text_field :code %>

      <%= f.label :identificationtype, "Identification Type" %>
      <%=f.select(:identificationtype,options_for_select([["CC", "CC"], ["CE", "CE"]]))%>       

      <%= f.label :identification %>
      <%= f.text_field :identification %>

      <%= f.label :status %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   

      <%= f.label :usertype,"User Type" %>
      <%=f.select(:usertype,options_for_select([["Estudiante", "Estudiante"], ["Coordinador", "Coordinador"], ["Profesor", "Profesor"]]))%>   

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>


  <%#= f.label :programs %>

      <%= select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name'), :multiple => (if :usertype then true else"Estudiante".eql?"Estudiante" end) %>


      <div class="submit">
        <%= f.submit "Agregar usuario", class: "btn btn-mc" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, "usuario") %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;max-width:480px;min-width:150px">
  <div class="title">
    <h1>

      <%= @user.firstname %> <%= @user.lastname %>
    </h1>

    <%= @user.code %>, <%= @user.identificationtype %>, <%= @user.identification %>, <%= @user.status %>, <%= @user.usertype %>, <%= @user.email %>
  </div>
  <div class="span6 offset3" >
    <% if @user.programs.any? %>
      <h3>Programs</h3>
      <ol class="programs">
        <%= render @programs %>
      </ol>
      <%= will_paginate @programs %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span8">

    <% if @user.preregister_subjects.any? %>
      <% if @user.usertype.eql?("Estudiante") && !@program.nil?%>
        <h3><%=I18n.t('usuario.preregistro')+" "+@program.name %></h3>
        <%= link_to "delete all", preregister_subject_path(:all => 1,:user_id =>@user.id,:program_id =>@program.id), method: :delete,
          data: { confirm: "You sure?" } %>
        <ol class="programs">
          <%= render @preregister_subjects %>
        </ol>
        <%= will_paginate @preregister_subjects %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/ver.html.erb
<% provide(:title, "usuario") %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;min-width:150px">
  <div class="title">
    <h1>
      <%= @user.firstname %> <%= @user.lastname %>
    </h1>
    Código: <%= @user.code %><br/>
    Identificación: <%= @user.identificationtype %> <%= @user.identification %><br/>
    Estado: <%= @user.status %><br/>
    Tipo de usuario: <%= @user.usertype %><br/>
    E-mail: <%= @user.email %><br/>
  </div>
  <div class="offset3" >
    <% if @user.programs.any? %>
      <h3>Programas</h3>
      <table  border="1">
        <tr>

          <th>Código</td>
          <th>Nombre</td>
          <th colspan="3">Acciones</th>  
        <tr>
          <%= render @programs, :locals => {:verusr =>"1"} %>
      </table>
    <% end %>
  </div>
  <div class="row">
    <div class="span8">

      <% if @user.preregister_subjects.any? %>

        <% if @user.usertype.eql?("Estudiante") && !@program.nil?%>

          <h3><%=I18n.t('usuario.preregistro')+" "+@program.name %></h3>
          <%= link_to "Eliminar todas", preregister_subjects_path(:all => 1,:user_id =>@user.id,:program_id =>@program.id), method: :delete, data: { confirm: "¿Esta seguro de realizar esta acción? \n Esta acción eliminara todo el historial de materias" } %>
          <table  border="1">
            <th>Código</th>
            <th>Nombre</th>
            <th>Estado</th>
            <th colspan="3">Acciones</th>
            <%= render @preregister_subjects %>
          </table>
          </ol>
          <%= will_paginate @preregister_subjects %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>