config/routes.rb
MasterClassNB::Application.routes.draw do
  get "teacher_subjects/index"
  get "teacher_subjects/show"
  get "teacher_subjects/new"
  get "teacher_subjects/create"
  get "teacher_subjects/edit"
  get "teacher_subjects/destroy"
  get "teacher_subjects/update"
  get "sessions/create"
  get "sessions/destroy"
  get "register_subjects/index"
  get "register_subjects/edit"
  get "register_subjects/create"
  get "subjects/new"
  get "subjects/index"
  get "subjects/edit"
  get "subjects/create"
  get "programs/create"
  get "programs/new"
  get "programs/index"
  get "programs/edit"
  get "semesters/new"
  get "semesters/index"
  get "semesters/edit"
  get "semesters/show"
  get "semesters/create"
  
  get "users/new"
  get "users/index"
  get "users/edit"
  get "users/show"
  
  
  match "estadisticas", to: 'estadisticas#index', via: 'get'
  match "users/cargar_usuarios", to: 'users#cargar_usuarios', via: 'get'
  match "users/mostrar", to: 'users#ver', via: 'get'
  
  

  match '/help', to: 'general#help', via: 'get'
  match '/about',   to: 'general#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  match '/preregister_subjects', to: 'preregister_subjects#update',     via: 'patch'  
  match '/preregister_subjects', to: 'preregister_subjects#destroy',     via: 'delete'  

  root 'sessions#new'
  
  resources :users
  resources :programs
  resources :subjects
  resources :semesters
  resources :preregister_subjects
  resources :sessions, only: [:new, :create, :destroy]

  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  before_save { self.code = code.upcase }
   
  validates :name, presence: true, length: { maximum: 200 }
  validates :code, presence: true, length: { maximum: 100 },  uniqueness: { case_sensitive: false }
  validates :quota, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :credits, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :status, presence: true
  
  has_many :teacher_subjects
  has_many :users, :through => :teacher_subjects
  
  has_many :subject_semesters
  has_many :semesters , :through => :subject_semesters
  
  has_many :subject_programs
  has_many :programs, :through => :subject_programs
  
  has_one :quota_config
  
  has_many :preregister_subjects
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :signed_in_user
  def new
    @subject = Subject.new
  end

  def index
    @subject_list =Subject.paginate(page: params[:page]).per_page(10)
  end

  def edit
    @subject =  Subject.find_by_id(params[:id])
  end
  
  def update
    @subject = Subject.find_by_id(params[:id])
    if @subject.update_attributes(subject_params)
      #        Actualizar programas a los que pertenece la materia
      flash[:success] = "Subject was updated"
      redirect_to subjects_path
    else
      flash[:success] = "Ocurrio un error actualizando al usuario"
      render "edit"
    end
  end
  
  def disable  
  end
  
  def show
    if !params[:disable].nil?
      @subject = Subject.find_by_id(params[:id])
      if params[:disable] == "1"
     
        @subject.update_attribute(:status, "Inactivo")
        flash[:success] = I18n.t('subject.deshabilitado') 
      else
        
        @subject.update_attribute(:status, "Activo")
        flash[:success] = I18n.t('subject.habilitado')
      end
    end
    redirect_to subjects_url
  end

  def create
    @subject = Subject.new(subject_params)    
    if @subject.save
      flash[:success] = 'Se ha guardado con éxito la materia'
      redirect_to subjects_url
    else
      if @subject.code.nil?
        flash[:error] = 'no hay codigo de programa, por favor ingreselo'    
      end
      render 'new'
    end
  end

  def destroy
    Subject.find(params[:id]).destroy
    flash[:success] = I18n.t('subject.eliminado') 
    redirect_to subjects_url
  end

  def subject_params
    params.require(:subject).permit(:name,:code,:quota,:credits,:status)
  end
  
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/views/subjects/_subject.html.erb
<tr>
  <td><%= "#{subject.code}" %></td>
  <td><%= "#{subject.name}" %></td>
  <td><%= "#{subject.quota}" %></td>
  <td><%= "#{subject.status}" %></td>
  <% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
    <td><%= link_to image_tag(('log_editar.png'), alt: I18n.t('editar')),  edit_subject_path(subject) %></td>
    <td>
      <% if subject.status == "Activo" %>
        <%= link_to image_tag(('log_desactivar.png'), alt: I18n.t('disable')), subject_path(subject,:disable => 1),
          data: { confirm: I18n.t('seguro') } %>
      <% end %>
      <% if subject.status == "Inactivo" %>
        <%= link_to image_tag(('log_desactivar.png'), alt: I18n.t('enable')), subject_path(subject,:disable => 0),
          data: { confirm: I18n.t('seguro') }  %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/subjects/create.html.erb
<h1>Subject#create</h1>
<p>Find me in app/views/subject/create.html.erb</p>

app/views/subjects/edit.html.erb
<% provide(:title, 'Edit subject') %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;max-width:480px;min-width:150px">
  <div class="title">
    <h1>Edit subject</h1>
  </div>
  <div class="span6 offset3" >
    <%= form_for(@subject) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>


      <%= f.label :code %>
      <%= f.text_field :code %>


      <%= f.label :quota %>
      <%= f.number_field :quota%>
    
      <%= f.label :credits %>
      <%= f.text_area :credits%>

      <%= f.label :status %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   


    <%= select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name'), :multiple => true %>

      <div class="submit">
        <%= f.submit "Editar materia", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/subjects/index.html.erb
<% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
  <div id="main1">
    <div id="main2">
      <div id="left">
        <div class="column-in">
          <h2>
            <p id="lccont" class="btn">
              <%= link_to image_tag('log_agregar.png')+"Agregar materia", subjects_new_path %>
            </p>
          </h2>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% unless @subject_list.nil? %>
  <% if @subject_list.size>0 %>
    <table  border="1">
      <th>Código</th>
      <th>Nombre</th>
      <th>Quota</th>
      <th>Estado</th>
          <% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
      <th colspan="3">Acciones</th>
      <% end %>
      <%= render @subject_list %>
    </table>
    <%= will_paginate @subject_list  %>


  <% else %> 
    <p>No existen materias disponibles</p>
  <% end %>  
<% end %>

app/views/subjects/new.html.erb
<% provide(:title, 'Crear materia') %>

<div class="formoid-default-skyblue" style="background-color:#FFFFFF;font-size:14px;font-family:'Open Sans','Helvetica Neue','Helvetica',Arial,Verdana,sans-serif;color:#666666;max-width:480px;min-width:150px">
  <div class="title">
    <h1>Crear materia</h1>
  </div>
  <div class="span6 offset3" >
    <%= form_for(@subject) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :code %>
      <%= f.text_field :code %>
    
      <%= f.label :quota %>
      <%= f.number_field :quota%>

      <%= f.label :credits %>
      <%= f.text_area :credits%>

      <%= f.label :status %>
      <%=f.select(:status,options_for_select([["Activo", "Activo"], ["Inactivo", "Inactivo"]]))%>   

      <%= f.label :programs %>
      <%= select_tag "programs", options_from_collection_for_select(Program.all, 'id', 'name'), :multiple => true %>

      <%= f.label :teacher %>
        <%= collection_select(:teacher_subject, :user_id, User.where(usertype: "Profesor"), :id, :firstname) %>

      <div class="submit">
        <%= f.submit "Agregar materia", class: "btn " %>
        </div>
      <% end %>
    </div>
  </div>