config/routes.rb
MasterClassNB::Application.routes.draw do
  get "teacher_subjects/index"
  get "teacher_subjects/show"
  get "teacher_subjects/new"
  get "teacher_subjects/create"
  get "teacher_subjects/edit"
  get "teacher_subjects/destroy"
  get "teacher_subjects/update"
  get "sessions/create"
  get "sessions/destroy"
  get "register_subjects/index"
  get "register_subjects/edit"
  get "register_subjects/create"
  get "subjects/new"
  get "subjects/index"
  get "subjects/edit"
  get "subjects/create"
  get "programs/create"
  get "programs/new"
  get "programs/index"
  get "programs/edit"
  get "semesters/new"
  get "semesters/index"
  get "semesters/edit"
  get "semesters/show"
  get "semesters/create"
  
  get "users/new"
  get "users/index"
  get "users/edit"
  get "users/show"
  
  
  match "estadisticas", to: 'estadisticas#index', via: 'get'
  match "users/cargar_usuarios", to: 'users#cargar_usuarios', via: 'get'
  match "users/mostrar", to: 'users#ver', via: 'get'
  
  

  match '/help', to: 'general#help', via: 'get'
  match '/about',   to: 'general#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  match '/preregister_subjects', to: 'preregister_subjects#update',     via: 'patch'  
  match '/preregister_subjects', to: 'preregister_subjects#destroy',     via: 'delete'  

  root 'sessions#new'
  
  resources :users
  resources :programs
  resources :subjects
  resources :semesters
  resources :preregister_subjects
  resources :sessions, only: [:new, :create, :destroy]

  

end

app/views/layouts/_footer.html.erb
<footer >
  <div id="footer">
    <div class="column-in">
      <div id="debug">
<%#= debug(params) if Rails.env.development? %>
      </div>
      <small>
        <%= link_to image_tag("masterclass_small.png", alt: "MasterClass"), root_path %> por Juan David Rodríguez
      </small>
      <nav>
        <ul>
          <li><%= link_to "About",   about_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</footer>


<%= javascript_include_tag "formoid-default-skyblue" %>

app/views/layouts/_header.html.erb
<header>

  <div id="header">
    <div id="left">
      <div class="column-in">
        <%= link_to image_tag("masterclass_medium.png", alt: "MasterClass"), root_path %>
      </div>
    </div>
 
    
    <div id="middle">
      <div class="column-in">
        <h1 style="margin-top: 100px;">MasterClass</h1>
      </div>
      <%#*<div class="row">%>
         <%#=image_tag("barratop.png", alt: "MasterClass", :class =>"style_image_border") %>
      <%#*</div>%>
    </div>
  </div>

</header>

app/views/layouts/_menu.html.erb
<nav>
  <ul class="nav pull-right">
    <% if signed_in? %>        
      <li class="menu-item">
        <%= link_to image_tag('log_usuario.png') + " Usuarios",    users_url %>
      </li>

      <li class="menu-item"><%= link_to image_tag('log_materias.png') + " Materias", subjects_url %></li>

      <% if current_user.usertype.eql?("Coordinador") || current_user.usertype.eql?("Admin") %>
        <li class="menu-item">
          <%= link_to image_tag('log_programas.png') +" Programas", programs_url %>
        </li>
        <li class="menu-item">
          <%= link_to image_tag('log_semtre.png') +" Semestres", semesters_url%>
        </li>
        <li class="menu-item">
          <%= link_to image_tag('log_estadisticas.png') +" Estadísticas", estadisticas_url%>
        </li>
      <% end %>
      <li class="menu-item">
        <%= link_to image_tag('logo-infopersonal.png') +" Información personal", users_mostrar_path(current_user,:id => current_user.id) %>
      </li>
      <li class="menu-item"><%= link_to image_tag('log_salir.png') +" Salir", signout_path, method: "delete" %></li>
      <% else %>
  <%#*<li class="menu-item"><%= link_to "Ingresar", signin_path </li>%>
      <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "aristo/theme" %>  
    <%= stylesheet_link_tag "prime-ui" %>   
    <%= javascript_include_tag "prime-ui" %>  
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body style="padding-top: 0px">
    <%= render 'layouts/header' %>
    <div id="container" >
      <div id="main1">
        <div id="main2">
          <div id="left">
            <div class="column-in">
              <%= render 'layouts/menu' %>
            </div>
          </div>
          <div id="right" >
            <div class="column-in">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>">
                  <%= value %>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>



    <%= render 'layouts/footer' %>



  </body>
</html>